name: deployment example 1
on: push
jobs:
    lint:
      runs-on: ubuntu-latest
      steps: 
       - name: download code
         uses: actions/checkout@v3
       - name: install dependancies
         run: npm ci
    Test:
      runs-on: ubuntu-latest
      steps: 
       - name: download code
         uses: actions/checkout@v3
       - name: install dependancies
         run: npm ci
       - name: Test
         run: npm run test

    Build:
      runs-on: ubuntu-latest
      steps: 
       - name: download code
         uses: actions/checkout@v3
       - name: install dependancies
         run: npm ci
       - name: Build code
         run: npm run build
    Deploy:
      runs-on: ubuntu-latest
      steps: 
       - name: download code
         uses: actions/checkout@v3
       - name: install dependancies
         run: npm ci
       - name: Deploy code
         run: echo "Deploying..."

    
