name: deployment example 1
on: push
Jobs:
  lint:
  run: ubuntu-latest
  steps: 
   - name: download code
     uses: actions/checkout@v3
   - name: install dependancies
     run: npm ci
  Test:
  run: ubuntu-latest
  steps: 
   - name: download code
     uses: actions/checkout@v3
   - name: install dependancies
     run: npm ci
   - name: Test
     run: npm run test
  
  Build:
  run: ubuntu-latest
  steps: 
   - name: download code
     uses: actions/checkout@v3
   - name: install dependancies
     run: npm ci
   - name: Build code
     run: npm run build
  Deploy:
  run: ubuntu-latest
  steps: 
   - name: download code
     uses: actions/checkout@v3
   - name: install dependancies
     run: npm ci
   - name: Deploy code
     run: echo "Deploying..."

    